function Home() {
    return <h1>DUDA EU TE AMOOOO!!<b/>
    ESPERO QUE COM ESSE CURSO EU CONSIGA TE AJUDAR NO SEU TRABALHO<b/>
    CRIANDO O SISTEMINHA QUE TE PROMETI S2.</h1>
}

export default Home;